name: Publish Packages

on:
  push:
    tags:
      - 'v*' # v0.0.1 or v0.0.1-beta.0

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Build All Workspaces
        run: yarn workspaces foreach -A -t run build
      - name: Bundle Frontend
        run: yarn workspace @appmana-public/auth-proxy-frontend run bundle
      - name: Publish to npm (Trusted Publishing)
        run: |

          if [[ "${{ github.ref_name }}" == *"-"* ]]; then
            NPM_TAG="next"
          else
            NPM_TAG="latest"
          fi

          yarn workspaces foreach -A --no-private npm publish --access public --npm-tag $NPM_TAG --tolerate-republish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_PUBLISH_PROVENANCE: "true"

  build-docker:
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Downcase Repo Name
        run: echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      - name: Build Context Setup
        run: |
          corepack enable
          yarn install --immutable
          yarn workspaces foreach -A -t run build

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: auth-proxy-backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}/auth-proxy-backend:latest
            ghcr.io/${{ env.REPO_LOWER }}/auth-proxy-backend:${{ github.ref_name }}